[workspace]
members = [
    "moddef",
    "option_kind",
    "result_kind",
    "repeat_until",
    "atomic_buffer",
    "transport",
    "transport_tcp",
    "networked",
    "spellcast",
    #"game",
    #"game_rps"
]