[package]
name = "repeat_until"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moddef = "0.2.2"
option_trait = "0.1.3"
result_kind = {path = "../result_kind"}