[package]
name = "stein_saks_papir"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
moddef = "0.2.2"
local-ip-address = "0.5.3"
thiserror = "1.0"
static_assertions = "1.1.0"